#!/usr/bin/env node
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const WORKER_NAME = "poi-cache";
const DB_NAME = "poi-cache";
const DB_BINDING = "DB";

const WRANGLER_CONFIG = path.join(__dirname, "wrangler.jsonc");
const SCHEMA_FILE = path.join(__dirname, "schema.sql");

// ---------------- helpers ----------------

function run(cmd, inherit = false) {
  console.log(`\n> ${cmd}`);
  return execSync(cmd, {
    stdio: inherit ? "inherit" : "pipe",
    encoding: "utf8"
  });
}

function tryRun(cmd) {
  try {
    execSync(cmd, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function stripJsonComments(text) {
  return text
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/.*$/gm, "");
}

// ---------------- setup steps ----------------

function ensureWrangler() {
  if (tryRun("wrangler --version")) {
    console.log("✔ Wrangler already installed");
    return;
  }
  console.log("📦 Installing Wrangler...");
  run("npm install -g wrangler", true);
}

function ensureLogin() {
  console.log("🔐 Logging into Cloudflare...");
  run("wrangler login", true);
}

function ensureD1Database() {
  console.log(`🗄️  Ensuring D1 database "${DB_NAME}" exists...`);
  const list = run("wrangler d1 list");
  if (list.includes(DB_NAME)) {
    console.log("✔ D1 database already exists");
    return;
  }
  run(`wrangler d1 create ${DB_NAME}`, true);
}

function ensureD1Binding() {
  console.log("🔗 Ensuring D1 binding in wrangler.jsonc...");

  if (!fs.existsSync(WRANGLER_CONFIG)) {
    throw new Error("wrangler.jsonc not found");
  }

  const raw = fs.readFileSync(WRANGLER_CONFIG, "utf8");
  const parsed = JSON.parse(stripJsonComments(raw));

  parsed.d1_databases ??= [];

  const exists = parsed.d1_databases.some(
    d => d.binding === DB_BINDING
  );

  if (exists) {
    console.log("✔ D1 binding already present");
    return;
  }

  parsed.d1_databases.push({
    binding: DB_BINDING,
    database_name: DB_NAME,
    database_id: ""
  });

  const output =
    "// Auto-generated by poi-cache installer\n" +
    JSON.stringify(parsed, null, 2) +
    "\n";

  fs.writeFileSync(WRANGLER_CONFIG, output);
  console.log("✔ D1 binding added");
}

function ensureSchema() {
  console.log("📐 Applying database schema...");
  run(`wrangler d1 execute ${DB_NAME} --file=${SCHEMA_FILE}`, true);
}

function deployWorker() {
  console.log("🚀 Deploying worker...");
  const out = run("wrangler deploy");

  const match = out.match(/https:\/\/[^\s]+\.workers\.dev/);
  if (match) {
    console.log(`\n🌍 Worker URL:\n${match[0]}`);
  } else {
    console.log("\nℹ️  Worker deployed (URL not detected)");
  }
}

// ---------------- main ----------------

try {
  console.log("🧭 POI Cache Worker Installer");

  ensureWrangler();
  ensureLogin();
  ensureD1Database();
  ensureD1Binding();
  ensureSchema();
  deployWorker();

  console.log("\n🎉 Installation complete!");
} catch (err) {
  console.error("\n❌ Installation failed");
  console.error(err.message || err);
  process.exit(1);
}
